M48
; DRILL file {KiCad 9.0.4} date 2025-12-30T15:29:52-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-30T15:29:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.630
%
G90
G05
T1
X125.312Y-104.781
T2
X125.312Y-98.781
M30
